
help:
	@echo "Usage:" 
	@echo "make clean		Cleans up the files created at build-time."
	@echo "make help		Shows this message"
	@echo
	@echo "Dependencies:"
	@echo "none"

clean:
	rm *.gch

.PHONY: help clean
